name: audiotagger
description: Library to read and write ID3 tags to MP3 files. You can get data as Map object or Tag object.
version: 1.0.5
homepage: https://github.com/Samurai016/Audiotagger

environment:
  flutter: ^1.10.0
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nicolorebaioli.audiotagger
        pluginClass: AudiotaggerPlugin